//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControlHoras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacientes()
        {
            this.horasMedicas = new HashSet<horasMedicas>();
        }
    
        public int idPaciente { get; set; }
        public string rutPaciente { get; set; }
        public string nombresPaciente { get; set; }
        public string appPaciente { get; set; }
        public string apmPaciente { get; set; }
        public string telefonoPaciente { get; set; }
        public string correoPaciente { get; set; }
        public bool sexoPaciente { get; set; }
        public int edadPaciente { get; set; }
        public string passwordPaciente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<horasMedicas> horasMedicas { get; set; }
    }
}
